# Generated by Django 6.1 on 2026-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('plan', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
